[storage]
driver = "overlay"
rootless_storage_path = "/home/vscode/.local/share/containers/storage"

[storage.options]
ignore_chown_errors = "true"

[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
ignore_chown_errors = "true"
